unstable_features = true
style_edition = "2027"

group_imports = "StdExternalCrate"
imports_granularity = "Module"
reorder_imports = true

use_field_init_shorthand = true
use_small_heuristics = "Max"
