[package]
name = "http-cgi-macros"
version = "0.1.0-alpha.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/JMontupet/http-cgi"
description = "Procedural macros for http-cgi"
keywords = ["http-cgi"]
categories = ["web-programming"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.5", features = ["full"] }
