[package]
name = "http-cgi"
version = "0.1.0-alpha.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/JMontupet/http-cgi"
description = "A bridge to handle CGI environments using standard Rust http crate types."
keywords = ["http", "cgi"]
categories = ["web-programming"]

[features]
default = ["macros"]
json = ["dep:serde", "dep:serde_json"]
macros = ["dep:http-cgi-macros"]

[dependencies]
http-cgi-macros = { version="0.1.0-alpha.1", path="../http-cgi-macros", optional = true }

bytes = "1.12.1"
http = "1.5.0"
thiserror = "2.0.20"

serde = { version = "1.0.229", optional = true }
serde_json = { version = "1.0.151", optional = true }
